### ISSUE TITLE
Rawgit crash on start

### ISSUE THREAD

**Issue by wehmoen** [rgrove/rawgit#142]
Hi I just cloned your repo, and used npm install without any problems.
But when I try npm start it says `app crashed`

    nico@noctem:/opt/rawgit> npm start
    
    > rawgit@0.0.1 start /opt/rawgit
    > NODE_ENV=development nodemon
    
    [nodemon] 1.11.0
    [nodemon] to restart at any time, enter `rs`
    [nodemon] watching: *.*
    [nodemon] starting `node index.js`
    /opt/rawgit/lib/middleware/file-redirect.js:6
    const { extensionWhitelist } = config;
          ^
    
    SyntaxError: Unexpected token {
        at exports.runInThisContext (vm.js:53:16)
        at Module._compile (module.js:373:25)
        at Object.Module._extensions..js (module.js:416:10)
        at Module.load (module.js:343:32)
        at Function.Module._load (module.js:300:12)
        at Module.require (module.js:353:17)
        at require (internal/module.js:12:17)
        at Object.<anonymous> (/opt/rawgit/lib/middleware/index.js:7:18)
        at Module._compile (module.js:409:26)
        at Object.Module._extensions..js (module.js:416:10)
    [nodemon] app crashed - waiting for file changes before starting...
    
Can you help me with that?

Kind regards,

wehmoen

**Comment by rgrove** [comment]
Sounds like you're using an old version of Node.js. I recommend using Node 7.
